spring.application.name=HealthcareEquipmentSystem
spring.datasource.url=jdbc:mysql://localhost:3306/HealthCareEquipmentSystemdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# JWT Configuration
jwt.secret=ThisIsASecretKeyForJwtThatMustBeAtLeast32CharsLong
# Expiration: 1 hour (3600000 ms)
jwt.expiration=3600000